# Generated by Django 4.1.2 on 2022-12-23 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0002_charttype_type_alter_charttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('data_file', models.FileField(upload_to='data/', verbose_name='Data')),
                ('chart_type', models.CharField(choices=[('BC', 'Bar Chart'), ('LC', 'Line Chart'), ('PC', 'Pie Chart')], max_length=5)),
                ('label', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChartType',
        ),
    ]
