# Generated by Django 4.1.2 on 2022-12-23 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_chart_delete_charttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='data_file',
            field=models.FileField(upload_to='data/', validators=[django.core.validators.FileExtensionValidator(['.xlsx'])], verbose_name='Data'),
        ),
    ]
