# Generated by Django 4.1.2 on 2022-12-24 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_alter_chart_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='data_file',
            field=models.FileField(upload_to='data/', validators=[django.core.validators.FileExtensionValidator(['xlsx'])], verbose_name='Data'),
        ),
    ]
