# Generated by Django 4.1.2 on 2022-12-24 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_alter_chart_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='data_file',
            field=models.FileField(blank=True, upload_to='data/', validators=[django.core.validators.FileExtensionValidator(['xlsx'])], verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='label',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='chart',
            name='value',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
